#!/bin/bash

cd "$(dirname "$0")"
if [[ -e DSAlign && -e DSAlign/venv && -e DSAlign/models/en && $# -eq 0 ]]; then
    exit 0
else
    echo "[+] Running setup"
fi

if [[ ! -e DSAlign/bin ]]; then
    echo '[+] Fetch submodule DSAlign'
    git submodule update --init --recursive
fi

cd DSAlign
echo '[+] Create DSAlign environment'
bin/createenv.sh
if [[ ! -e models/en/output_graph.pb ]]; then
    echo '[+] Fetch DSAlign model'
    bin/getmodel.sh
fi
if [[ ! -e dependencies/kenlm ]]; then
    echo '[+] Build KenLM'
    bin/lm-dependencies.sh
fi

. venv/bin/activate
pip install sentencepiece
