#!/bin/bash

if [[ $# -lt 1 ]]; then
    echo "Usage: wplay <clips.lst> [...clips.lst]"
    exit 1
fi

for clips_lst in "$@"; do
    dir=$(dirname "$clips_lst")
    while read line; do
        parts=( $line )
        clip=${parts[1]}
        if [[ ! -e "$clip" ]]; then
             # try to rebase
             clip="$dir/clips/${clip##/*/}"
             [[ -e "$clip" ]] || continue
        fi
        text=$(echo "$line" | cut -d' ' -f4-)
        echo "[+] $text | $clip"
        play -q "$clip" 2>&1 silence 1 0.1 1% 1 0.1 1% speed 1.25 || exit
    done < "$clips_lst"
done
