#!/bin/bash
IFS=$'\n'
for lst in "$@"; do
    echo "[-] $lst"
    sum=$(awk '{sum+=$3}; END {printf "%.3f\n", sum}' "$lst")
    hours=$(echo "scale=3; $sum / 1000.0 / 60.0 / 60.0" | bc -l)
    count=$(wc -l "$lst" | awk '{print $1}')
    echo "  $count clips"
    echo "  $hours hours"
done
